FROM arm64v8/node:12.19.0-buster
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -yq \
  build-essential && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install
COPY . .

CMD ["node", "index.js"]