FROM node:12.19.0
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -yq \
  build-essential && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY . .
RUN npm install

CMD ["node", "index.js"]